require("dotenv").config();

module.exports={
JWT_SECRET : process.env.JWT_SECRET,
EMAIL_HOST : process.env.EMAIL_HOST,
EMAIL_PORT : process.env.EMAIL_PORT,
EMAIL_USER : process.env.EMAIL_USER,
EMAIL_PASS : process.env.EMAIL_PASS,

PORT : process.env.PORT,
DB_URL : process.env.DB_URL ,
CLOUD_NAME : process.env.CLOUD_NAME,
CLOUDINARY_API_KEY : process.env.CLOUDINARY_API_KEY ,
CLOUDINARY_API_SECRET : process.env.CLOUDINARY_API_SECRET,




SMTP_USER : process.env.SMTP_USER,
SMTP_PASS : process.env.SMTP_PASS,

FRONTEND_URL : process.env.FRONTEND_URL,
FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
FIREBASE_PRIVATE_KEY_ID: process.env.FIREBASE_PRIVATE_KEY_ID,
FIREBASE_PRIVATE_KEY: process.env.FIREBASE_PRIVATE_KEY,
FIREBASE_CLIENT_EMAIL: process.env.FIREBASE_CLIENT_EMAIL,
FIREBASE_CLIENT_ID: process.env.FIREBASE_CLIENT_ID,
}